Add more Bash helper functions and improve script robustness

diff --git a/bash/apt-common b/bash/apt-common
--- a/bash/apt-common
+++ b/bash/apt-common
@@ -1,5 +1,19 @@
 assert_apt_available
 
+function apt_require_package() {
+
+    if get_confirmation "$(basename "$0") needs to install the $1 package. Is that OK?" Y Y; then
+
+        sudo apt-get install -y "$1" || die
+
+    else
+
+        die
+
+    fi
+
+}
+
 function apt_refresh_packages() {
 
     APT_INSTALLED_PACKAGES="$(dpkg-query -f '${binary:Package}\n' -W)"
@@ -14,27 +28,27 @@ function apt_refresh_packages() {
 function apt_package_installed() {
 
     apt_make_cache_clean
-    echo "$APT_INSTALLED_PACKAGES" | grep -E "^$1"'(:.*)?$' &>/dev/null
+    echo "$APT_INSTALLED_PACKAGES" | grep -E "^$1"'(:.*)?$' >/dev/null 2>&1
 
 }
 
 function apt_package_just_installed() {
 
-    echo "$(printf '%s\n' "${APT_JUST_INSTALLED[@]}")" | grep -E "^$1"'(:.*)?$' &>/dev/null
+    echo "$(printf '%s\n' "${APT_JUST_INSTALLED[@]}")" | grep -E "^$1"'(:.*)?$' >/dev/null 2>&1
 
 }
 
 function apt_package_available() {
 
     apt_make_cache_clean
-    echo "$APT_AVAILABLE_PACKAGES" | grep -E "^$1"'(:.*)?$' &>/dev/null
+    echo "$APT_AVAILABLE_PACKAGES" | grep -E "^$1"'(:.*)?$' >/dev/null 2>&1
 
 }
 
 function apt_package_is_gui() {
 
     apt_make_cache_clean
-    apt_package_available "$1" && echo "$APT_GUI_PACKAGES" | grep -E "^$1"'(:.*)?$' &>/dev/null
+    apt_package_available "$1" && echo "$APT_GUI_PACKAGES" | grep -E "^$1"'(:.*)?$' >/dev/null 2>&1
 
 }
 
@@ -144,9 +158,9 @@ function apt_ubuntu_archive_url() {
 
 function do_apt_enable_ubuntu_repository() {
 
-    if ! cat /etc/apt/sources.list | grep -E '^deb[[:space:]]+https?://([[:alnum:]]+\.)?archive\.ubuntu\.com/ubuntu/?[[:space:]]+'"$1"'[[:space:]]+.*\b'"$2"'\b' &>/dev/null; then
+    if ! cat /etc/apt/sources.list | grep -E '^deb[[:space:]]+https?://([[:alnum:]]+\.)?archive\.ubuntu\.com/ubuntu/?[[:space:]]+'"$1"'[[:space:]]+.*\b'"$2"'\b' >/dev/null 2>&1; then
 
-        command -v add-apt-repository &>/dev/null || apt_force_install_packages "software-properties-common"
+        command_exists add-apt-repository || apt_force_install_packages "software-properties-common"
 
         sudo add-apt-repository -yn "deb $(apt_ubuntu_archive_url) $1 $2"
 
@@ -176,9 +190,9 @@ function apt_enable_partner_repository() {
 
     assert_is_ubuntu
 
-    if ! cat /etc/apt/sources.list | grep -E '^deb[[:space:]]+https?://([[:alnum:]]+\.)?archive\.canonical\.com/ubuntu/?[[:space:]]+'"$DISTRIB_CODENAME"'[[:space:]]+.*\bpartner\b' &>/dev/null; then
+    if ! cat /etc/apt/sources.list | grep -E '^deb[[:space:]]+https?://([[:alnum:]]+\.)?archive\.canonical\.com/ubuntu/?[[:space:]]+'"$DISTRIB_CODENAME"'[[:space:]]+.*\bpartner\b' >/dev/null 2>&1; then
 
-        command -v add-apt-repository &>/dev/null || apt_force_install_packages "software-properties-common"
+        command_exists add-apt-repository || apt_force_install_packages "software-properties-common"
 
         sudo add-apt-repository -yn "deb http://archive.canonical.com/ubuntu $DISTRIB_CODENAME partner"
 
@@ -191,7 +205,7 @@ function apt_enable_partner_repository() {
 # Usage: apt_register_ppa "the/ppa" "package1 package2 ..." [add immediately (Y/N)]
 function apt_register_ppa() {
 
-    command -v add-apt-repository &>/dev/null || apt_force_install_packages "software-properties-common"
+    command_exists add-apt-repository || apt_force_install_packages "software-properties-common"
 
     local p PREFERENCES=
 
@@ -210,7 +224,7 @@ EOF
 
     fi
 
-    if ! cat /etc/apt/sources.list /etc/apt/sources.list.d/*.list 2>/dev/null | grep "^[^#]*/$1" &>/dev/null; then
+    if ! cat /etc/apt/sources.list /etc/apt/sources.list.d/*.list 2>/dev/null | grep "^[^#]*/$1" >/dev/null 2>&1; then
 
         for p in $2; do
 
@@ -237,14 +251,14 @@ EOF
 
 function apt_add_key_from_url() {
 
-    wget -qO - "$1" | sudo apt-key add - &>/dev/null || die "Error: unable to add GPG key from $1"
+    wget -qO - "$1" | sudo apt-key add - >/dev/null 2>&1 || die "Error: unable to add GPG key from $1"
 
 }
 
 # Usage: apt_register_repository my-repo-identifier "https://gpg.key.url" "content for my-repo-identifier.list" "package1 package2 ..." [add immediately (Y/N)]
 function apt_register_repository() {
 
-    command -v wget &>/dev/null || apt_force_install_packages "wget"
+    command_exists wget || apt_force_install_packages "wget"
 
     local p
 
@@ -616,19 +630,13 @@ function apt_deb_path() {
 
 }
 
-# Usage: apt_install_deb "http://url.to/package.deb" [delete cached (Y/N)] [queue only (Y/N)]
+# Usage: apt_install_deb "http://url.to/package.deb" [queue only (Y/n)]
 function apt_install_deb() {
 
-    command -v wget &>/dev/null || apt_force_install_packages "wget"
-
-    if [ "${2:-N}" = "Y" ]; then
-
-        rm -f "$(apt_deb_path "$1")"
-
-    fi
+    command_exists wget || apt_force_install_packages "wget"
 
     # queue by default
-    if [ "${3:-Y}" = "Y" ]; then
+    if [ "${2:-Y}" = "Y" ]; then
 
         APT_DEB_QUEUE+=("$1")
 
@@ -824,7 +832,7 @@ function apt_upgrade_all() {
 # returns all changed configuration files (note: deleted files aren't detected)
 function apt_get_changed_configuration_files() {
 
-    command -v debsums &>/dev/null || apt_force_install_packages "debsums"
+    command_exists debsums || apt_force_install_packages "debsums"
 
     sudo debsums -ce 2>/dev/null
 
@@ -833,7 +841,7 @@ function apt_get_changed_configuration_files() {
 # returns all new files under /etc
 function apt_get_new_configuration_files() {
 
-    command -v debsums &>/dev/null || apt_force_install_packages "debsums"
+    command_exists debsums || apt_force_install_packages "debsums"
 
     sudo find /etc -type f | grep -vFf <(
         set -euo pipefail
diff --git a/bash/common b/bash/common
--- a/bash/common
+++ b/bash/common
@@ -1,5 +1,16 @@
 set -euo pipefail
 
+function error_trap() {
+
+    echo "Error: $(basename "$0") failed with exit code $1 in $2 at line $3" >&2
+    exit $1
+
+}
+
+trap 'error_trap "$?" "${BASH_SOURCE[0]}" "$LINENO"' ERR
+
+set -E
+
 SCRIPT_ARGS=("$@")
 
 function assert_is_macos() {
@@ -57,10 +68,11 @@ function assert_apt_available() {
 function assert_is_ubuntu_lts() {
 
     assert_is_ubuntu
+    assert_function_exists "apt_require_package"
 
-    command -v ubuntu-distro-info &>/dev/null || apt_request_package "distro-info"
+    command_exists ubuntu-distro-info || apt_require_package "distro-info"
 
-    if ! ubuntu-distro-info --supported-esm | grep "^${DISTRIB_CODENAME}\$" &>/dev/null; then
+    if ! ubuntu-distro-info --supported-esm | grep "^${DISTRIB_CODENAME}\$" >/dev/null 2>&1; then
 
         die "Error: $(basename "$0") is only supported on LTS releases of Ubuntu"
 
@@ -88,9 +100,35 @@ function assert_not_root() {
 
 }
 
+function assert_command_exists() {
+
+    if ! command_exists "$1"; then
+
+        die "Error: $(basename "$0") requires $1"
+
+    fi
+
+}
+
+function assert_function_exists() {
+
+    if ! function_exists "$1"; then
+
+        die "Error: $(basename "$0") requires Bash function $1"
+
+    fi
+
+}
+
 function command_exists() {
 
-    command -v "$1" &>/dev/null
+    command -v "$1" >/dev/null 2>&1
+
+}
+
+function function_exists() {
+
+    declare -F "$1" >/dev/null 2>&1
 
 }
 
@@ -133,7 +171,7 @@ function echocn() {
 
 function die() {
 
-    [ "$#" -gt "0" ] && echoc "$@" >&2
+    [ "$#" -gt "0" ] && echoc "$@" >&2 || true
 
     exit 1
 
@@ -148,19 +186,19 @@ function console_message() {
     shift
     echocn "==> " "$@"
     echocn "$MESSAGE1"
-    [ -n "$MESSAGE2" ] && echocn " $MESSAGE2" "$@"
+    [ -n "$MESSAGE2" ] && echocn " $MESSAGE2" "$@" || true
     echo
 
 }
 
-# Usage: get_confirmation "Do this?" [default response (Y/N)] [force valid response? (Y/N)] && { do_it; }
+# Usage: get_confirmation "Do this?" [default response (y/n)] [force valid response? (y/N)] && { do_it; }
 function get_confirmation() {
 
     local PROMPT=() DEFAULT="${2:-}" FORCE="${3:-N}" YN
 
-    [ -n "$1" ] && PROMPT+=("$1")
+    [ -n "$1" ] && PROMPT+=("$1") || true
 
-    case DEFAULT in
+    case "$DEFAULT" in
 
     Y)
         PROMPT+=("[Y/n]")
@@ -210,7 +248,7 @@ function file_to_array() {
 
         for PATTERN in "$@"; do
 
-            [[ "$LINE" =~ $PATTERN ]] && continue 2
+            [[ "$LINE" =~ $PATTERN ]] && continue 2 || true
 
         done
 
@@ -235,7 +273,6 @@ function single_or_plural() {
 
 }
 
-# because we can't rely on BASH 4+
 function upper_first() {
 
     echo "$(echo "$1" | cut -c1 | tr "[:lower:]" "[:upper:]")$(echo "$1" | cut -c2-)"
@@ -289,7 +326,7 @@ function offer_sudo_password_bypass() {
     FILENAME="/etc/sudoers.d/nopasswd-$USERNAME"
     CHECK_FILENAME="$RS_CONFIG_DIR/.nopasswd-$USERNAME"
 
-    [ -e "$CHECK_FILENAME" ] && return
+    [ -e "$CHECK_FILENAME" ] && return || true
 
     console_message "Please provide your computer password if requested" "" $BLUE
 
@@ -297,7 +334,7 @@ function offer_sudo_password_bypass() {
 
         if get_confirmation "Allow user ${BOLD}${USERNAME}${RESET} to skip future password prompts?"; then
 
-            sudo tee "$FILENAME" >/dev/null <<EOF && sudo chmod 0440 "$FILENAME"
+            sudo tee "$FILENAME" >/dev/null <<EOF && sudo chmod 0440 "$FILENAME" || die
 ${USERNAME} ALL=(ALL) NOPASSWD:ALL
 EOF
 
@@ -310,11 +347,11 @@ EOF
     fi
 
     # save time next time
-    touch "$CHECK_FILENAME"
+    touch "$CHECK_FILENAME" || die
 
 }
 
-# Usage: sed_escape_search "text to escape" [extended regular expressions? (Y/N)]
+# Usage: sed_escape_search "text to escape" [extended regular expressions? (Y/n)]
 function sed_escape_search() {
 
     if [ "${2:-Y}" = "Y" ]; then
@@ -340,12 +377,12 @@ function git_add_global_ignore() {
 
     local i IGNORE_FILE
 
-    IGNORE_FILE="$(git config --global core.excludesFile)"
+    IGNORE_FILE="$(git config --global core.excludesFile)" || die "Error: Git global option core.excludesFile not defined"
     IGNORE_FILE="${IGNORE_FILE/#\~/$HOME}"
 
-    [ -f "$IGNORE_FILE" ] || touch "$IGNORE_FILE"
+    [ -f "$IGNORE_FILE" ] || touch "$IGNORE_FILE" || die
 
-    [ -f "$IGNORE_FILE" ] || return 1
+    [ -f "$IGNORE_FILE" ] || die "Error: unable to create file $IGNORE_FILE"
 
     for i in "$@"; do
 
@@ -359,10 +396,10 @@ function git_add_global_ignore() {
 
 }
 
-# Usage: git_add_global_setting <setting.name> <value> [change if already set? (Y/N, default N)]
+# Usage: git_add_global_setting <setting.name> <value> [change if already set? (y/N)]
 function git_add_global_setting() {
 
-    if [ "${3:-N}" = "Y" ] || ! git config --global "$1" &>/dev/null; then
+    if [ "${3:-N}" = "Y" ] || ! git config --global "$1" >/dev/null 2>&1; then
 
         local EXTRA=()
 
@@ -411,8 +448,16 @@ function apply_system_config() {
 
 }
 
+# results are returned in document order without de-duplication
+function get_urls_from_url() {
+
+    # from: https://daringfireball.net/2009/11/liberal_regex_for_matching_urls
+    wget -qO - "$1" | grep -Po '\b(([\w-]+://?|www[.])[^\s()<>]+(?:\([\w\d]+\)|([^[:punct:]\s]|/)))'
+
+}
+
 RS_SCRIPT_PATH="${BASH_SOURCE[0]}"
-[ -L "$RS_SCRIPT_PATH" ] && RS_SCRIPT_PATH="$(readlink "$RS_SCRIPT_PATH")"
+if command -v realpath >/dev/null 2>&1; then RS_SCRIPT_PATH="$(realpath "$RS_SCRIPT_PATH")"; fi
 RS_ROOT_DIR="$(cd "$(dirname "$RS_SCRIPT_PATH")/.." && pwd -P)"
 RS_CONFIG_DIR="$RS_ROOT_DIR/config"
 RS_CACHE_DIR="$RS_ROOT_DIR/cache"
@@ -484,9 +529,9 @@ Linux)
 
     fi
 
-    command -v X &>/dev/null || IS_SERVER=1
+    command_exists X || IS_SERVER=1
 
-    if command -v lsb_release &>/dev/null; then
+    if command_exists lsb_release; then
 
         DISTRIB_ID="$(lsb_release -si)"
         LSB_RELEASE_EXTRA=
@@ -514,8 +559,8 @@ Linux)
     IS_APT_INSTALLED=1
     IS_SNAP_INSTALLED=1
 
-    { command -v apt-get &>/dev/null && command -v dpkg &>/dev/null; } || IS_APT_INSTALLED=0
-    command -v snap &>/dev/null || IS_SNAP_INSTALLED=0
+    { command_exists apt-get && command_exists dpkg; } || IS_APT_INSTALLED=0
+    command_exists snap || IS_SNAP_INSTALLED=0
 
     ;;
 
