Add lk_apply_settings and related functions

diff --git a/bash/common-functions b/bash/common-functions
--- a/bash/common-functions
+++ b/bash/common-functions
@@ -134,10 +134,21 @@ function lk_escape() {
         [ "$i" -eq "0" ] || [ "$REPLACE" != "${SPECIAL[0]}" ] || continue
         SEARCH="\\$REPLACE"
         [ "$REPLACE" != "\\" ] || REPLACE="\\\\"
+        [ "$REPLACE" != "}" ] || REPLACE="\\}"
         eval "STRING=\"\${STRING//$SEARCH/$ESCAPE$REPLACE}\""
         ((++i))
     done
     echo "$STRING"
+}
+
+function lk_escape_ere() {
+    # shellcheck disable=SC1003
+    lk_escape "$1" '$' '(' ')' '*' '+' '.' '/' '?' '[' '\' ']' '^' '{' '|' '}'
+}
+
+function lk_escape_ere_replace() {
+    # shellcheck disable=SC1003
+    lk_escape "$1" '&' '/' '\'
 }
 
 # lk_replace find replace_with string
@@ -156,6 +167,12 @@ function lk_upper() {
     [ "$#" -gt "0" ] &&
         echo "$*" | tr '[:lower:]' '[:upper:]' ||
         tr '[:lower:]' '[:upper:]'
+}
+
+function lk_trim() {
+    [ "$#" -gt "0" ] &&
+        echo "$1" | sed -Ee 's/^\s+//' -e 's/\s+$//' ||
+        sed -Ee 's/^\s+//' -e 's/\s+$//'
 }
 
 function lk_get_hostname() {
@@ -431,6 +448,41 @@ function lk_ubuntu_at_least() {
     lk_is_ubuntu && lk_version_at_least "$(lsb_release -sr)" "$1"
 }
 
+# lk_apply_setting file_path setting_name setting_value [delimiter] [comment_chars] [space_chars]
+# shellcheck disable=SC2005
+function lk_apply_setting() {
+    local FILE_PATH="$1" SETTING_NAME="$2" SETTING_VALUE="$3" DELIMITER="${4:-=}" \
+        COMMENT_PATTERN SPACE_PATTERN NAME_ESCAPED VALUE_ESCAPED DELIMITER_ESCAPED CHECK_PATTERN SEARCH_PATTERN REPLACE REPLACED
+    COMMENT_PATTERN="${5:+[$(lk_escape_ere "$5")]*}"
+    SPACE_PATTERN="${6:+[$(lk_escape_ere "$6")]*}"
+    NAME_ESCAPED="$(lk_escape_ere "$SETTING_NAME")"
+    VALUE_ESCAPED="$(lk_escape_ere "$SETTING_VALUE")"
+    DELIMITER_ESCAPED="$(lk_trim "$DELIMITER")"
+    [ -n "$DELIMITER_ESCAPED" ] || DELIMITER_ESCAPED="$DELIMITER"
+    DELIMITER_ESCAPED="$(lk_escape_ere "$DELIMITER_ESCAPED")"
+    CHECK_PATTERN="^$NAME_ESCAPED$SPACE_PATTERN$DELIMITER_ESCAPED$SPACE_PATTERN$VALUE_ESCAPED$SPACE_PATTERN\$"
+    grep -Eq "$CHECK_PATTERN" "$FILE_PATH" || {
+        REPLACE="$SETTING_NAME$DELIMITER$SETTING_VALUE"
+        # try to replace an uncommented value first
+        SEARCH_PATTERN="^$SPACE_PATTERN$NAME_ESCAPED$SPACE_PATTERN$DELIMITER_ESCAPED.*\$"
+        REPLACED="$(sed -E "0,/$SEARCH_PATTERN/{s/$SEARCH_PATTERN/$(lk_escape_ere_replace "$REPLACE")/}" "$FILE_PATH")" || return
+        # failing that, try for a commented one
+        grep -Eq "$CHECK_PATTERN" <<<"$REPLACED" || {
+            SEARCH_PATTERN="^$COMMENT_PATTERN$SPACE_PATTERN$NAME_ESCAPED$SPACE_PATTERN$DELIMITER_ESCAPED.*\$"
+            REPLACED="$(sed -E "0,/$SEARCH_PATTERN/{s/$SEARCH_PATTERN/$(lk_escape_ere_replace "$REPLACE")/}" "$FILE_PATH")" || return
+        }
+        [ -f "$FILE_PATH.orig" ] || lk_maybe_sudo cp -pv "$FILE_PATH" "$FILE_PATH.orig" || return
+        if grep -Eq "$CHECK_PATTERN" <<<"$REPLACED"; then
+            lk_maybe_sudo tee "$FILE_PATH" <<<"$REPLACED" >/dev/null || return
+        else
+            {
+                echo "$REPLACED"
+                echo "$REPLACE"
+            } | lk_maybe_sudo tee "$FILE_PATH" >/dev/null || return
+        fi
+    }
+}
+
 function lk_load_env() {
     local i j DELIMITED_PATH IFS ADD ADD_FIRST ADD_TO_PATH=(${ADD_TO_PATH[@]+"${ADD_TO_PATH[@]}"} "$LK_ROOT/bin") ADD_TO_PATH_FIRST=("$HOME/.local/bin" ${ADD_TO_PATH_FIRST[@]+"${ADD_TO_PATH_FIRST[@]}"})
     ! lk_is_macos || ADD_TO_PATH+=("$LK_ROOT/bin/macos")
@@ -465,6 +517,50 @@ function lk_load_env() {
 function lk_user_in_group() {
     [ "$(comm -12 <(groups "$1" | sed -E 's/^.*://' | grep -Eo '[^[:space:]]+' | sort) <(lk_echo_array "${@:2}" | sort | uniq) | wc -l)" -gt "0" ]
 }
+
+function lk_get_firefox_profile() {
+    local INI_PATH PROFILE_PATH
+    INI_PATH="$HOME/.mozilla/firefox/installs.ini"
+    [ -f "$INI_PATH" ] &&
+        PROFILE_PATH="$HOME/.mozilla/firefox/$(grep -m 1 '^Default=' "$INI_PATH" | sed 's/^Default=//')" || return
+    echo "$PROFILE_PATH"
+}
+
+# lk_set_firefox_pref pref_name raw_value
+function lk_set_firefox_pref() {
+    local USERJS_PATH PREF_LINE USERJS
+    USERJS_PATH="$(lk_get_firefox_profile)/user.js" || return
+    [ -f "$USERJS_PATH" ] || touch "$USERJS_PATH" || return
+    PREF_LINE="user_pref(\"$1\", $2);"
+    grep -Fxq "$PREF_LINE" "$USERJS_PATH" || {
+        USERJS="$(sed -E "/^user_pref\(\"$(lk_escape_ere "$1")\"/d" "$USERJS_PATH")" || return
+        {
+            [ -z "$USERJS" ] || echo "$USERJS"
+            echo "$PREF_LINE"
+        } >"$USERJS_PATH"
+    }
+}
+
+function lk_open_firefox_ssb() (
+    if lk_set_firefox_pref "browser.ssb.enabled" "true"; then
+        nohup firefox --ssb "$@" </dev/null >/dev/null 2>&1 &
+    else
+        nohup firefox "$@" </dev/null >/dev/null 2>&1 &
+    fi
+    disown
+)
+
+function lk_open_chrome_ssb() (
+    local CHROME_COMMAND INSTANCE_NAME
+    for CHROME_COMMAND in google-chrome-stable google-chrome; do
+        lk_command_exists "$CHROME_COMMAND" || continue
+        INSTANCE_NAME="$(echo "$1" | sed -Ee 's/^https?:\/\/([^/]+)(\/.*)?$/\1_\2/' -e 's/\//_/g' -e 's/[_]+$//')"
+        nohup "$CHROME_COMMAND" --user-data-dir="$HOME/.config/$INSTANCE_NAME" --no-first-run --enable-features=OverlayScrollbar --app="$1" "${@:2}" </dev/null >/dev/null 2>&1 &
+        disown
+        return
+    done
+    return 1
+)
 
 # lk_make_iso path1...
 function lk_make_iso() {
@@ -578,6 +674,16 @@ EOF
         sysctl -ar 'net\..*\.(((default|all)\.rp_filter|tcp_syncookies|ip_forward|all\.forwarding)|accept_ra)$'
     }
 
+    function lk_install_icon() {
+        local SIZE SIZES=(16x16 24x24 32x32 48x48 64x64 96x96 128x128 256x256 512x512 1024x1024)
+        [ -f "$1" ] || return
+        for SIZE in "${SIZES[@]}"; do
+            mkdir -p "$HOME/.local/share/icons/hicolor/$SIZE/apps" &&
+                convert "$1" -resize "$SIZE" "$HOME/.local/share/icons/hicolor/$SIZE/apps/$(basename "$1")" || return
+        done
+        ! lk_command_exists gtk-update-icon-cache || gtk-update-icon-cache --force --ignore-theme-index --quiet "$HOME/.local/share/icons/hicolor" || true
+    }
+
 }
 
 ! lk_is_arch || {
@@ -591,16 +697,12 @@ EOF
         mkdir -p "$LK_ROOT/cache/aur" || return
         ERRORS=($(
             for AUR in "$@"; do
-                sleep 1
-                while [ "$(jobs -p | wc -l)" -gt "3" ]; do
-                    sleep 1
-                done
                 ( 
                     (
                         cd "$LK_ROOT/cache/aur" || exit
                         if [ ! -d "$AUR" ]; then
                             lk_console_item "Cloning" "https://aur.archlinux.org/$AUR.git"
-                            git clone "https://aur.archlinux.org/$AUR.git" &&
+                            git clone "https://aur.archlinux.org/$AUR.git" >/dev/null &&
                                 cd "$AUR" ||
                                 exit
                         else
@@ -611,7 +713,7 @@ EOF
                                         BEHIND="$(git rev-list --count 'HEAD..@{u}')" || exit
                                     if [ "$BEHIND" -gt "0" ]; then
                                         rm -f "$LATEST_FILENAME"
-                                        git merge --ff-only || exit
+                                        git merge --ff-only >/dev/null || exit
                                     fi
                                 }
                             } || exit
