Add git version check before submodule check

diff --git a/bash/common-dev b/bash/common-dev
--- a/bash/common-dev
+++ b/bash/common-dev
@@ -2,6 +2,14 @@
 
 assert_command_exists realpath
 
+function git_version_is_at_least() {
+
+    [ -n "${GIT_VERSION:-}" ] || GIT_VERSION="$(git --version | gnu_grep -Pom 1 '(?<=\s|^)[0-9.]+(?=\s|$)')" || die "Unable to parse output from \"git --version\""
+
+    version_is_at_least "$GIT_VERSION" "$1"
+
+}
+
 function git_get_code_roots() {
 
     local KEY
@@ -38,11 +46,11 @@ function git_is_dir_working_root() {
 
     local ROOT_PATH="$1" IN_WORK_TREE SUPERPROJECT TOPLEVEL
 
-    [ -d "$1" ] || die "Error: $1 is not a directory"
+    [ -d "$ROOT_PATH" ] || die "Error: $ROOT_PATH is not a directory"
 
     ROOT_PATH="$(realpath "$ROOT_PATH")"
 
-    pushd "$1" >/dev/null || die
+    pushd "$ROOT_PATH" >/dev/null || die
 
     # 1. repo directory? (exits non-zero with error output otherwise)
     # 2. *working* repo directory? (i.e. not bare or inside .git)
@@ -50,8 +58,12 @@ function git_is_dir_working_root() {
     [ "$IN_WORK_TREE" = "true" ] || pop_return1
 
     # 3. not a submodule?
-    SUPERPROJECT="$(git rev-parse --show-superproject-working-tree)" || die
-    [ -z "$SUPERPROJECT" ] || pop_return1
+    if git_version_is_at_least 2.13; then
+
+        SUPERPROJECT="$(git rev-parse --show-superproject-working-tree)" || die
+        [ -z "$SUPERPROJECT" ] || pop_return1
+
+    fi
 
     # 4. top-level directory?
     TOPLEVEL="$(git rev-parse --show-toplevel)" || die
