Fix portability issues w/Bash 3.2 and add package management abstraction

diff --git a/bash/common b/bash/common
--- a/bash/common
+++ b/bash/common
@@ -1,5 +1,5 @@
 #!/bin/bash
-# shellcheck disable=SC2034
+# shellcheck disable=SC2034,SC2206,SC2207
 
 set -euo pipefail
 
@@ -35,6 +35,30 @@ function exit_trap() {
 trap exit_trap EXIT
 
 ORIGINAL_BASH_SUBSHELL="$BASH_SUBSHELL"
+ORIGINAL_ARGUMENTS=("$@")
+
+function gnu_command() {
+
+    local COMMAND
+
+    COMMAND="$1"
+    shift
+
+    if [ "$IS_MACOS" -eq "1" ]; then
+
+        command_exists "g${COMMAND}" && COMMAND="g${COMMAND}" || echoc "Warning: GNU $COMMAND not available; $(basename "0") may not work as expected" >&2
+
+    fi
+
+    "$COMMAND" "$@"
+
+}
+
+function gnu_grep() {
+
+    gnu_command grep "$@"
+
+}
 
 function assert_is_macos() {
 
@@ -367,6 +391,12 @@ function array_join_by() {
 
 }
 
+function has_argument() {
+
+    array_search "$1" ORIGINAL_ARGUMENTS >/dev/null
+
+}
+
 function offer_sudo_password_bypass() {
 
     # don't proceed if there's no point
@@ -662,7 +692,9 @@ function dir_make_and_own() {
 
     assert_not_root
 
-    { [ -d "$1" ] || sudo mkdir -p "$1"; } && sudo chown "$(id -un):$(id -gn)" "$1"
+    [ -d "$1" ] || sudo mkdir -p "$1" || die
+
+    [ -w "$1" ] || sudo chown "$(id -un):$(id -gn)" "$1" || die
 
 }
 
@@ -671,6 +703,17 @@ function windows_running_as_administrator() {
     assert_command_exists whoami.exe
 
     whoami.exe /groups | grep '\bS-1-5-32-544\b.*\bEnabled group\b' >/dev/null
+
+}
+
+# because Bash 3.2 exits when eval exits non-zero, regardless of context or errexit status
+function eval_test() {
+
+    local EXIT_CODE
+
+    EXIT_CODE="$(eval 'if' "$@" '; then echo "0"; else echo "1"; fi')"
+
+    return "$EXIT_CODE"
 
 }
 
@@ -684,7 +727,7 @@ function link_settings() {
 
     if [ -n "${RUNNING_CHECK:-}" ]; then
 
-        if eval "$RUNNING_CHECK"; then
+        if eval_test "$RUNNING_CHECK"; then
 
             die "Error: $APP_NAME is currently running"
 
@@ -720,6 +763,95 @@ function link_settings() {
         ln -sv "$TO" "${LINK_FROM[$i]}"
 
     done
+
+}
+
+# Usage: install_or_queue "Description of this group" "item1 item2 ..." <allow user override? (y/n)> <singular noun> <plural noun> <name of "installed items" array> <name of "available items" array> <name of "to install" array to fill> [name of "already installed" array to fill]
+function install_or_queue() {
+
+    local REQUESTED=($2) UI="$3" SINGLE="$4" PLURAL="$5" ITEMS_INSTALLED ITEMS_AVAILABLE INSTALL_TARGET="$8" ALREADY_INSTALLED_TARGET="${9:-}"
+
+    local i=6 j k
+    for j in ITEMS_INSTALLED ITEMS_AVAILABLE; do
+
+        # k="$6"
+        eval 'k="$'"$i"'"'
+
+        if [ -z "$k" ]; then
+
+            eval "$j"'=()'
+
+        elif variable_exists "$k"; then
+
+            # ITEMS_INSTALLED=($(printf '%s\n' "${NAME_OF_ARRAY[@]}" | sort | uniq))
+            eval "$j"'=($(printf '"'"'%s\n'"'"' "${'"$k"'[@]}" | sort | uniq))'
+
+        else
+
+            # ITEMS_INSTALLED=($(COMMAND | sort | uniq))
+            eval "$j"'=($('"$k"' | sort | uniq))'
+
+        fi
+
+        ((i += 1))
+
+    done
+
+    local INSTALL UNAVAILABLE ALREADY_INSTALLED
+
+    console_message "Checking $1..." "" "$CYAN"
+
+    INSTALL=($(comm -23 <(printf '%s\n' "${REQUESTED[@]}" | sort | uniq) <([ "${#ITEMS_INSTALLED[@]}" -gt "0" ] && printf '%s\n' "${ITEMS_INSTALLED[@]}" || true)))
+    ALREADY_INSTALLED=($(comm -12 <(printf '%s\n' "${REQUESTED[@]}" | sort | uniq) <([ "${#ITEMS_INSTALLED[@]}" -gt "0" ] && printf '%s\n' "${ITEMS_INSTALLED[@]}" || true)))
+
+    if [ "${#ALREADY_INSTALLED[@]}" -gt "0" ] && [ -n "$ALREADY_INSTALLED_TARGET" ]; then
+
+        eval "$ALREADY_INSTALLED_TARGET"'+=("${ALREADY_INSTALLED[@]}")'
+
+    fi
+
+    if [ "${#INSTALL[@]}" -gt "0" ]; then
+
+        if [ "${#ITEMS_AVAILABLE[@]}" -gt "0" ]; then
+
+            UNAVAILABLE=($(comm -23 <(printf '%s\n' "${INSTALL[@]}" | sort | uniq) <(printf '%s\n' "${ITEMS_AVAILABLE[@]}")))
+
+            if [ "${#UNAVAILABLE[@]}" -gt "0" ]; then
+
+                console_message "${#UNAVAILABLE[@]} $(single_or_plural "${#UNAVAILABLE[@]}" "$SINGLE" "$PLURAL") unavailable for installation:" "${UNAVAILABLE[*]}" "$BOLD" "$RED"
+
+                INSTALL=($(comm -12 <(printf '%s\n' "${INSTALL[@]}" | sort | uniq) <(printf '%s\n' "${ITEMS_AVAILABLE[@]}")))
+
+                [ "${#INSTALL[@]}" -gt "0" ] || return 0
+
+            fi
+
+        fi
+
+        if [ "$UI" = "Y" ]; then
+
+            console_message "Missing ${#INSTALL[@]} $1 $(single_or_plural "${#INSTALL[@]}" "$SINGLE" "$PLURAL"):" "${INSTALL[*]}" "$BOLD" "$MAGENTA"
+
+            get_confirmation "Add the $1 $(single_or_plural "${#INSTALL[@]}" "$SINGLE" "$PLURAL") listed above?" Y Y || return 0
+
+        else
+
+            console_message "Adding ${#INSTALL[@]} $1 $(single_or_plural "${#INSTALL[@]}" "$SINGLE" "$PLURAL"):" "${INSTALL[*]}" "$GREEN"
+
+        fi
+
+        if variable_exists "$INSTALL_TARGET"; then
+
+            eval "$INSTALL_TARGET"'+=("${INSTALL[@]}")'
+
+        else
+
+            # shellcheck disable=SC2086
+            eval $INSTALL_TARGET "${INSTALL[@]}"
+
+        fi
+
+    fi
 
 }
 
