Add in_array

diff --git a/bash/common-homebrew b/bash/common-homebrew
--- a/bash/common-homebrew
+++ b/bash/common-homebrew
@@ -1,5 +1,6 @@
 #!/bin/bash
 # shellcheck disable=SC2034,SC2206,SC2207
+# Reviewed: 2019-11-04
 
 function brew_check() {
 
@@ -72,14 +73,14 @@ function brew_refresh() {
 function brew_formula_installed() {
 
     brew_make_cache_clean
-    echo "$BREW_INSTALLED_FORMULAE" | grep -E '^'"$1"'$' >/dev/null 2>&1
+    echo "$BREW_INSTALLED_FORMULAE" | grep -F "$1" >/dev/null 2>&1
 
 }
 
 function brew_cask_installed() {
 
     brew_make_cache_clean
-    echo "$BREW_INSTALLED_CASKS" | grep -E '^'"$1"'$' >/dev/null 2>&1
+    echo "$BREW_INSTALLED_CASKS" | grep -F "$1" >/dev/null 2>&1
 
 }
 
@@ -87,7 +88,7 @@ function brew_formula_just_installed() {
 
     if [ "${#BREW_JUST_INSTALLED[@]}" -gt "0" ]; then
 
-        printf '%s\n' "${BREW_JUST_INSTALLED[@]}" | grep -E '^'"$1"'$' >/dev/null 2>&1
+        printf '%s\n' "${BREW_JUST_INSTALLED[@]}" | grep -F "$1" >/dev/null 2>&1
 
     else
 
@@ -103,7 +104,7 @@ function brew_formula_installed_or_queued() {
 
         if [ "${#BREW_FORMULA_QUEUE[@]}" -gt "0" ]; then
 
-            printf '%s\n' "${BREW_FORMULA_QUEUE[@]}" | grep -E '^'"$1"'$' >/dev/null 2>&1
+            printf '%s\n' "${BREW_FORMULA_QUEUE[@]}" | grep -F "$1" >/dev/null 2>&1
 
         else
 
@@ -122,7 +123,7 @@ function brew_formula_installed_or_queued() {
 function brew_formula_available() {
 
     brew_make_cache_clean
-    echo "$BREW_AVAILABLE_FORMULAE" | grep -E '^'"$1"'$' >/dev/null 2>&1
+    echo "$BREW_AVAILABLE_FORMULAE" | grep -F "$1" >/dev/null 2>&1
 
 }
 
@@ -136,7 +137,7 @@ function brew_make_cache_clean() {
 
     if [ "$BREW_CACHE_DIRTY" -ne "0" ]; then
 
-        console_message "Updating lists..." "" "$CYAN"
+        console_message "Updating Homebrew formula and cask lists..." "" "$CYAN"
 
         brew update && brew_refresh && BREW_CACHE_DIRTY=0 || die
 
@@ -172,7 +173,7 @@ function brew_remove_formulae() {
     # shellcheck disable=SC2048
     for p in $*; do
 
-        if brew_formula_installed "$p" && ! array_search "$p" BREW_FORMULA_REMOVE_QUEUE >/dev/null; then
+        if brew_formula_installed "$p" && ! in_array "$p" BREW_FORMULA_REMOVE_QUEUE; then
 
             BREW_FORMULA_REMOVE_QUEUE+=("$p")
 
@@ -190,7 +191,7 @@ function brew_remove_casks() {
     # shellcheck disable=SC2048
     for p in $*; do
 
-        if brew_cask_installed "$p" && ! array_search "$p" BREW_CASK_REMOVE_QUEUE >/dev/null; then
+        if brew_cask_installed "$p" && ! in_array "$p" BREW_CASK_REMOVE_QUEUE; then
 
             BREW_CASK_REMOVE_QUEUE+=("$p")
 
@@ -258,13 +259,13 @@ function brew_upgrade_all() {
 
     console_message "Installing all available formula updates..." "" "$GREEN"
 
-    brew upgrade || die
+    brew upgrade || die "\"brew upgrade\" failed"
 
     if is_macos; then
 
         console_message "Installing all available cask updates..." "" "$GREEN"
 
-        brew cask upgrade --no-quarantine || die
+        brew cask upgrade --no-quarantine || die "\"brew cask upgrade\" failed"
 
         # see https://github.com/Homebrew/brew/issues/6112
         rm -fv "$HOME/Library/Caches/Homebrew/Cask/adoptopenjdk8"* \
@@ -272,7 +273,7 @@ function brew_upgrade_all() {
 
     fi
 
-    brew cleanup || die
+    brew cleanup || die "\"brew cleanup\" failed"
 
 }
 
