Complete git-update.sh

diff --git a/bash/common-dev b/bash/common-dev
--- a/bash/common-dev
+++ b/bash/common-dev
@@ -1,5 +1,7 @@
 #!/bin/bash
 
+assert_command_exists realpath
+
 function git_get_code_roots() {
 
     local KEY
@@ -20,7 +22,68 @@ function git_get_code_roots() {
 
         [ -d "${CODE_ROOTS[$KEY]}" ] || unset "CODE_ROOTS[$KEY]"
 
+        CODE_ROOTS[$KEY]="$(realpath "${CODE_ROOTS[$KEY]}")"
+
     done
+
+}
+
+function git_is_dir_working_root() {
+
+    local ROOT_PATH="$1" IN_WORK_TREE SUPERPROJECT TOPLEVEL
+
+    [ -d "$1" ] || die "Error: $1 is not a directory"
+
+    ROOT_PATH="$(realpath "$ROOT_PATH")"
+
+    pushd "$1" >/dev/null || die
+
+    # 1. repo directory? (exits non-zero with error output otherwise)
+    # 2. *working* repo directory? (i.e. not bare or inside .git)
+    IN_WORK_TREE="$(git rev-parse --is-inside-work-tree 2>/dev/null)" || pop_return1
+    [ "$IN_WORK_TREE" = "true" ] || pop_return1
+
+    # 3. not a submodule?
+    SUPERPROJECT="$(git rev-parse --show-superproject-working-tree)" || die
+    [ -z "$SUPERPROJECT" ] || pop_return1
+
+    # 4. top-level directory?
+    TOPLEVEL="$(git rev-parse --show-toplevel)" || die
+
+    popd >/dev/null
+
+    [ "$TOPLEVEL" = "$ROOT_PATH" ]
+
+}
+
+function git_format_remotes() {
+
+    local REMOTE REMOTE_URL REMOTES=()
+
+    for REMOTE in "$@"; do
+
+        REMOTE_URL="$(git remote get-url "$REMOTE")"
+        [ -z "$REMOTE_URL" ] || REMOTE_URL="($REMOTE_URL)"
+        REMOTES+=("${BOLD}${REMOTE}${RESET}${REMOTE_URL}")
+
+    done
+
+    echo "${NO_WRAP}${REMOTES[*]}${WRAP}"
+
+}
+
+# Usage: git_format_branch "branch_name" [commits behind] [commits ahead]
+function git_format_branch() {
+
+    local BRANCH BRANCH_EXTRA=()
+
+    BRANCH="${BOLD}${1}${RESET}"
+
+    [ "${2:-0}" -eq "0" ] || BRANCH_EXTRA+=("behind $2")
+    [ "${3:-0}" -eq "0" ] || BRANCH_EXTRA+=("ahead $3")
+    [ "${#BRANCH_EXTRA[@]}" -eq "0" ] || BRANCH="${BRANCH}[$(array_join_by "," "${BRANCH_EXTRA[@]}")]"
+
+    echo "$BRANCH"
 
 }
 
